language: python
cache: pip
dist: xenial

jobs:
  include:
    #########
    # Style #
    #########
    - stage: Style Checking
      python: "3.7"
      install:
        - pip install black
      script:
        - black . --check

    ############
    # Building #
    ############
    # 3.6 #
    - stage: Building
      python: "3.6"
      install:
        - pip install -r requirements.txt
        - pip install -r dev.requirements.txt
      script:
        - python manage.py --help
    # 3.7 #
    - stage: Building
      python: "3.7"
      install:
        - pip install -r requirements.txt
        - pip install -r dev.requirements.txt
      script:
        - python manage.py --help
    # Latest #
    - stage: Building
      python: "3.7"
      install:
        - pip install -r requirements.txt
        - pip install -r dev.requirements.txt
        - pip install django --upgrade
      script:
        - python manage.py --help
    ###########
    # Testing #
    ###########
    # 3.7 #
    - stage: Testing
      python: "3.7"
      install:
        - pip install -r requirements.txt
        - pip install -r dev.requirements.txt
      script:
        - pytest
        - retVal=$?
        - if [ $retVal -eq 5 ]; then
          exit 0
          else
          exit 1
          fi
